services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: pip install -r sexybot/requirements.txt
    startCommand: python sexybot/run_fixed_bot.py
    healthCheckPath: /health
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.11